"""Renomear coluna password

Revision ID: ebb065c362f4
Revises: 
Create Date: 2025-05-06 16:29:03.746477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb065c362f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=80), nullable=False))
        batch_op.drop_column('passoword')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passoword', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
